#!/bin/bash
set -e

LUAV=jit
LUAV=5.1
LUAV=5.2
LUAV=5.3
LUAV=5.4

compile_lua() {
  luac$LUAV -o "$2" "$1"
}
compile_lua_s() {
  luac$LUAV -s -o "$2" "$1"
}
if [ "$LUAV" == 5.1 ]; then
  INC=/usr/include/lua5.1
elif [ "$LUAV" == 5.2 ]; then
  INC=/usr/include/lua5.2
elif [ "$LUAV" == 5.3 ]; then
  INC=/usr/include/lua5.2
elif [ "$LUAV" == 5.4 ]; then
  INC=/home/siffiejoe/.self/programs/lua5.4
elif [ "$LUAV" == jit ]; then
  INC=/home/siffiejoe/.self/programs/luajit-2.0/include/luajit-2.0
  compile_lua() {
    luajit -bg "$1" "$2"
  }
  compile_lua_s() {
    luajit -bs "$1" "$2"
  }
else
  echo "invalid Lua version: $LUAV!" 1>&2
  exit 1
fi
gcc -Wall -Wextra -fpic -I"$INC" -shared -o light.so light.c
gcc -Wall -Wextra -fpic -I"$INC" -shared -o newproxy.so newproxy.c
compile_lua bytecode.lua bytecode.n.luac
compile_lua_s bytecode.lua bytecode.s.luac

for i in `seq 1 8`; do
  echo "running microscope$i.test.lua"
  lua$LUAV microscope$i.test.lua
done

for f in *.dot; do
  if [ -f "$f" ]; then
    img="${f%.dot}.gif"
    echo "making $img..."
    dot -T gif -o "$img" "$f"
  fi
done

exit 0

rm -f *.dot *.gif *.luac *.so
